### PR TITLE
adding white space to eof

### PR DESCRIPTION
**Pull request by shimwell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.
It looks like a sporadic failure resulted in the https://github.com/conda-forge/openmc-feedstock/pull/42 not merging correctly with master
https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=5658&_a=summary

This is an empty PR with no real changes (other than a single extra line). As suggested on the conda forge glitter https://gitter.im/conda-forge/conda-forge.github.io

Hoping to fix https://github.com/conda-forge/openmc-feedstock/issues/43

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by shimwell** [comment]
Discussed with @paulromano on slack, merging in

**Comment by carterbox** [comment]
🤞🏼

**Comment by shimwell** [comment]
It worked :tada: thanks @carterbox

**Pull request merged**
