### PR TITLE
Pydep

### PR DESCRIPTION
**Pull request by scopatz**
Potential fix for #11

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @conda-forge/core, any idea why adding a python as a build dep and rerendering with conda-smithy v3.1.2 did not produce CIs that depend on the Python version.  It is only building for Python 3.6, even though it should be building for 2.7, 3.5 and 3.6.  See #11

**Comment by msarahan** [comment]
The manual pin in https://github.com/conda-forge/openmc-feedstock/pull/12/files#diff-e178b687b10a71a3348107ae3154e44cR38 is breaking conda-build's auto-pinning stuff.

Better to use:

```
build:
  skip: True   # [py2k]
```

and not put any constraint on python in the deps

**Comment by scopatz** [comment]
Oh I see Ok.  I'll try that.  That pin isn't relevamnt to conda-forge at all, since it is >=2.7

**Comment by scopatz** [comment]
That seemed to work, thanks @msarahan!

**Pull request merged**
